apiVersion: apps/v1
kind: Deployment
metadata:
  name: micrortsapi
  labels:
    app: micrortsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micrortsapi
  template:
    metadata:
      labels:
        app: micrortsapi
    spec:
      containers:
        - name: micrortsapi
          env:
            - name: DB_HOST
              valueFrom:
               secretKeyRef:
                 name: my-secret
                 key: my-secret
                 value: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: my-secret
                  value: DB_USER
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: my-secret
                  value: DB_PWD
          image: gcr.io/microrts-sample/microrts.api:1.0.0
          ports:
            - containerPort: 8080
